version: '3.7'
services:
  apus-api:
    container_name: apus-api
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - apus-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  apus-db:
    container_name: apus-db
    image: postgres:13.0
    networks:
      - apus-network
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  apus-network:
    driver: bridge

volumes:
  pgdata:
